services:
  app-front:
    build:
      context: ./frontend
    image: app-front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./frontend:/frontend
    depends_on:
      - app-back

  app-back:
    build:
      context: ./backend
    image: app-back
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./backend:/backend
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres:18
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER-!ChangeMe!}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-!ChangeMe!}
      - POSTGRES_DB=${POSTGRES_DB-!ChangeMe!}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  
volumes:
  postgres_data:
    driver: local

